export function properties() {
    return {
        category: "Category:",
        subCategory: "Subcategory:",
        type1: "Apartment",
        type2: "House",
        type3: "Commercial",
        type4: "Others",
        subTypeFlat1: "1+kk",
        subTypeFlat2: "1+1",
        subTypeFlat3: "2+kk",
        subTypeFlat4: "2+1",
        subTypeFlat5: "3+kk",
        subTypeFlat6: "3+1",
        subTypeFlat7: "4+kk",
        subTypeFlat8: "4+1",
        subTypeFlat9: "5+kk",
        subTypeFlat10: "5+1",
        subTypeFlat11: "6 plus",
        subTypeFlat12: "Atypical",
        subTypeFlat13: "Room",
        subTypeHouse1: "Cottage",
        subTypeHouse2: "Family",
        subTypeHouse3: "Villa",
        subTypeHouse4: "Homestead",
        rooms1: "1 room",
        rooms2: "2 rooms",
        rooms3: "3 rooms",
        rooms4: "4 rooms",
        rooms5: "5 rooms plus",
        rooms6: "Atypical",
        subTypeCommercial1: "Office",
        subTypeCommercial2: "Warehouse",
        subTypeCommercial3: "Business premises",
        subTypeCommercial4: "Accomodation",
        subTypeCommercial5: "Restaurant",
        subTypeCommercial6: "Agriculture",
        subTypeCommercial7: "Apartment building",
        subTypeCommercial8: "Apartments",
        subTypeCommercial9: "Others",
        subTypeOthers1: "Garage",
        subTypeOthers2: "Wine cellar",
        subTypeOthers3: "Attic",
        subTypeOthers4: "Mobilheim",
    };
}
